# azure:
#   activedirectory:
#     tenant-id: 3fd11e85-d8ce-4c7f-b6a0-816346615777
#     client-id: 35cea567-1674-40d4-95a4-e0bf5314f89f
#     client-secret: xxx
#     user-group:
#       allowed-groups: 7d9e422c-b567-41a8-8ea2-52d86344d794, readers, writers